services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - [setFramework, ['@contao.framework']]

    contao_calendar.listener.generate_page:
        class: Contao\CalendarBundle\EventListener\GeneratePageListener
        arguments:
            - '@contao.framework'
        tags:
            - { name: contao.hook, hook: generatePage }

    contao_calendar.listener.insert_tags:
        class: Contao\CalendarBundle\EventListener\InsertTagsListener
        arguments:
            - '@contao.framework'
        tags:
            - { name: contao.hook, hook: replaceInsertTags }

    contao_calendar.listener.preview_url_convert:
        class: Contao\CalendarBundle\EventListener\PreviewUrlConvertListener
        arguments:
            - '@contao.framework'
        tags:
            - kernel.event_listener

    contao_calendar.listener.preview_url_create:
        class: Contao\CalendarBundle\EventListener\PreviewUrlCreateListener
        arguments:
            - '@request_stack'
            - '@contao.framework'
        tags:
            - kernel.event_listener

    contao_calendar.picker.event_provider:
        class: Contao\CalendarBundle\Picker\EventPickerProvider
        arguments:
            - '@knp_menu.factory'
            - '@router'
            - '@?translator'
            - '@security.helper'
        tags:
            - { name: contao.picker_provider, priority: 96 }
